#!/usr/bin/env python3
"""
store.py - read the index, and turn every hit into a citation someone can open.

This is the whole of the retrieval and provenance layer for the node's first
surface, and it imports NOTHING that is not in the Python standard library.

WHY NO FASTAPI, WHICH `NODE-ARCHITECTURE.md` §6 PROPOSES.
That section is a proposal, and it says so: *"where this document proposes
something §7 does not say, it is a proposal until §7 is amended."* Three reasons
to amend it rather than follow it:

  1. **§5.5.4 requires everything vendored and pinned, with no install step that
     needs a network.** FastAPI pulls starlette, pydantic, pydantic-core (a
     compiled Rust extension), anyio, sniffio, typing-extensions and a server.
     That is a wheel set to acquire, pin, verify, and re-acquire for macOS/arm64
     - the same work the geospatial toolchain took two days over.
  2. **§3.3 ranks repairability with commodity parts**, and §8.10 requires a
     second person to rebuild this from printed instructions. `http.server` is in
     every Python. A pinned pydantic-core wheel is not.
  3. **It buys nothing here.** This layer has four routes, no auth, no
     validation beyond integers, and one user.

If the node ever needs concurrency this cannot give, that is the moment to
revisit - and by then it will be replacing something that works.

THE SPARSE PATH NEEDS NO MODEL AND NO VECTOR STORE.
BM25 lives in SQLite FTS5, and `sqlite3` ships with Python. Provenance lives in
`provenance.sqlite3`. So keyword search with full citations runs with the
embedding model unloaded and Chroma untouched: the cheapest useful thing the node
can do, which matters because constraint 3.1 is priority one. The dense half is
loaded lazily and only if it is asked for; if `chromadb` is absent the layer says
so and keeps working, which is §3.4 rather than an apology.
"""

import importlib.util
import json
import os
import re
import sqlite3
import threading
import traceback
import urllib.parse
# stdlib only, and this is the only XML in the retrieval layer: library.xml
# is the one file here written by another program.
import xml.etree.ElementTree as ET

# The archive root. Everything else is derived, so a node with the archive on a
# different drive changes one environment variable.
ROOT = os.environ.get("ARK_ROOT") or os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INDEX = os.path.join(ROOT, "10-index")
BIN = os.path.join(ROOT, "bin")
BM25_DB = os.path.join(INDEX, "bm25.sqlite3")
PROV_DB = os.path.join(INDEX, "provenance.sqlite3")
# THE REGISTRY index-build.py WRITES, and the only record that knows about
# the most recent pass. `self.artifacts` comes from provenance.sqlite3, which
# is rebuilt separately and AFTER a build, so between the two it is behind:
# on 2026-09-24 the registry held 50 artifacts and 39,073,563 chunks while
# provenance still held 48 and 6,926,271. A coverage check that read the
# provenance table would have compared one stale record against another and
# reported no gap.
SOURCES = os.path.join(INDEX, "sources.json")
BOOKS = os.path.join(INDEX, "kiwix-books.json")
CHUNKS = os.path.join(INDEX, "chunks")
# Generated by bin/index-mirror-set.py; see the index quality filter notes in
# Store for what it holds and why it is a file rather than a query. Its absence
# is not an error - it means the mirror rule does not fire.
MIRROR_SET = os.path.join(INDEX, "mirror-mdwiki.json")
# The flat PQ64 index bin/index-pq-build.py writes. ABSENT IS A NORMAL STATE:
# this node ran on Chroma alone until 2026-09-15 and still can.
PQ_DIR = os.path.join(INDEX, "pq")
# Candidates the quantized index nominates before the exact rerank scores them.
# 400, RE-MEASURED AT 6,926,271 VECTORS ON 2026-09-15 and raised from 200.
# index-pq-probe.py over 43 real questions against exhaustive inner product:
#
#     depth 200    r@5 0.977    5 genuine misses    33.0 ms
#     depth 400    r@5 0.995    1 genuine miss      38.6 ms
#
# GENUINE, because the probe now separates a miss from a tie. Every r@1 miss at
# both depths was a duplicate scoring IDENTICALLY to the row it displaced, so
# r@1 is 1.000 at both once ties are counted; the r@5 misses are real passages
# the candidate list did not contain, and depth 400 recovers four of the five.
# The cost is 5.6 ms and 400 KB more of mmap reads per query, against an LLM
# turn measured in seconds.
#
# The evidence is the frozen 24 questions of 2026-09-08, not the 19 added the
# same day - the pass-2 questions score at or near 1.000 at both depths and
# decide nothing here. See DECISIONS 2026-09-15.
#
# ARK_RERANK_DEPTH still overrides, which is how the sweep is run against a
# running node without editing this file.
RERANK_DEPTH = int(os.environ.get("ARK_RERANK_DEPTH", "400"))

# ---------------------------------------------------------------------------
# THE FIRST `import numpy` HAPPENS ONCE, ON ONE THREAD. Added 2026-09-16 after a
# node that had been up three hours answered a medical question KEYWORD ONLY and
# reported, in /api/health:
#
#   ImportError: cannot import name 'NDArray' from partially initialized module
#   'numpy._typing' (most likely due to a circular import)
#   [__init__.py:4 <- defmatrix.py:13 <- __init__.py:87 <- _linalg.py:76]
#
# That is numpy reaching into itself while still initializing: one thread is
# partway through `import numpy`, a second asks for something inside it, finds
# `sys.modules["numpy"]` already present, believes it is finished, and touches a
# module that is still being built. Nothing was wrong with the venv - the same
# interpreter imported numpy 2.5.2 cleanly from a shell, and `serve.py
# --selftest` had loaded PQ over 6,926,271 vectors under it the same night.
#
# THIS MODULE MADE IT REACHABLE. `_load_pq` imports faiss and numpy under
# `self._pq_lock`; `_load_dense` imports chromadb and sentence_transformers
# under `self._dense_lock`. Both pull numpy and THE TWO LOCKS DO NOT EXCLUDE
# EACH OTHER, on a process that also runs cross-check jobs, spatial and safety
# on their own threads.
#
# WHICH THREAD WAS SECOND IS NOT KNOWN AND THE FIX DOES NOT DEPEND ON IT. If
# numpy is fully imported before any request thread exists, no thread can ever
# see it half-built. `serve.py` calls preimport() on the main thread at startup;
# the lock below covers whatever reaches this module first when it has not.
#
# IT DOES NOT TOUCH THE LAZY LOAD. numpy is about 0.1 s and ~30 MB and pulls in
# neither faiss, nor the 443 MB index, nor bge-m3, so the 2026-09-15 decision -
# a node that never asks a dense question never pays for one - is unchanged.
_IMPORT_LOCK = threading.Lock()
_NUMPY_READY = False
# THE VERSION THAT ACTUALLY LOADED, recorded 2026-09-17 so the startup line can
# name it. `numpy 2.5.2` is an observation of this process; `numpy is installed`
# would be an inference from the filesystem, and the whole 2026-09-16 entry is
# about the difference.
_NUMPY_VERSION = None


def preimport():
    """Import numpy once, under a lock this module shares across both loaders.

    RAISES on failure, so both call sites record the real exception through the
    handler they already have rather than through a string. Idempotent and cheap
    after the first call: one lock acquisition and a bool.

    `numpy.linalg` is named explicitly because it is where the observed failure
    re-entered - importing the parent alone would leave the same submodule to be
    pulled in later by faiss or torch, on whatever thread got there first."""
    global _NUMPY_READY, _NUMPY_VERSION
    if _NUMPY_READY:
        return
    with _IMPORT_LOCK:
        if _NUMPY_READY:
            return
        import numpy                                          # noqa: F401
        import numpy.linalg                                   # noqa: F401
        _NUMPY_VERSION = getattr(numpy, "__version__", None)
        _NUMPY_READY = True


def numpy_version():
    """The numpy this process imported, or None if it never got that far.

    Deliberately NOT `import numpy; numpy.__version__` on demand: that would
    answer "what would import now", and this has to answer "what DID import, on
    the main thread, at startup" - which on 2026-09-16 were different answers.
    numpy 2.5.2 imported cleanly from a shell all evening while the running
    server could not import it at all."""
    return _NUMPY_VERSION

# Where kiwix-serve is expected. The URL shapes below were read out of the
# vendored binary itself - 09-software/kiwix-tools, kiwix-serve 3.8.2 - and not
# from documentation for some other version:
#     raw content   <root>/content/<book>/<path>
#     viewer chrome <root>/viewer#<book>/<path>
KIWIX = os.environ.get("ARK_KIWIX", "http://localhost:8080").rstrip("/")

RRF_K = 60


def _quasi(path):
    """Percent-encode a path, leaving the separators alone.

    NOT COSMETIC. Two real entries in this archive break an unencoded URL:

        appropedia   Are_You_Ready?/Floods
        fao          Irrigation/Respuesta del rendimiento de los cultivos al agua.pdf

    The first carries a literal `?`, which starts a query string the moment it
    lands in a path - so /content/<book>/Are_You_Ready?/Floods asks kiwix-serve
    for `Are_You_Ready` with a query, and gets a 404. The second carries spaces.
    Both were found by reading the first four results of the first three test
    questions, which is the argument for testing against the real corpus rather
    than a fixture.

    `safe="/"` is what kiwix-serve's own viewer does - its source calls the
    result `quasiUriEncodedPath`, encoding everything except the separator, and
    matching it is how a link built here opens in the viewer built there."""
    return urllib.parse.quote(path, safe="/")


def _load_bin(name):
    """Import a tool from bin/ by path. Their filenames carry hyphens, so they are
    not importable by name, and renaming them would break every runbook that
    names them.

    KNOWN COUPLING, RECORDED RATHER THAN HIDDEN: the stoplist lives in
    bin/index-bm25.py and this reuses it instead of copying it. A second copy
    would drift, and the stoplist is the file where drift is least acceptable -
    it is hand-tuned for THIS corpus, where `well` is a water well. When
    13-ark-node becomes its own repository, bin/ moves into it as ops/ per
    NODE-ARCHITECTURE §6 and this import becomes local."""
    path = os.path.join(BIN, name)
    if not os.path.exists(path):
        raise RuntimeError("%s is missing; the node cannot search without it" % path)
    spec = importlib.util.spec_from_file_location(name.replace("-", "_")[:-3], path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod



class _Rows(list):
    """What `Shared.execute` hands back: rows already fetched.

    Returning a live cursor would defeat the lock, because the statement stays
    open until the caller finishes iterating and another thread can reach it in
    the meantime. Everything the node asks of this index is small enough to
    materialise."""

    def fetchone(self):
        return self[0] if self else None

    def fetchall(self):
        return list(self)


def expand_followup(q, prev_qs):
    """The retrieval string for a follow-up, or None if there is nothing to add.

    A thin delegate to `bin/index-bm25.py`, which owns the tokenizer and the
    stoplist. The coupling is the one `_load_bin` documents at length: a second
    copy of a stoplist hand-tuned for THIS corpus, where `well` is a water well,
    is the drift least worth risking. Guarded because §3.4 does not let a
    retrieval path require something that can be absent - no `bin/`, no
    expansion, and the follow-up is retrieved as the standalone question it
    looks like."""
    try:
        return _load_bin("index-bm25.py").expand_followup(q, prev_qs)
    except Exception:                                # noqa: BLE001 - optional
        return None


class Shared(object):
    """A read-only SQLite connection that several request threads may use.

    `check_same_thread=False` switches off Python's own check and puts nothing
    in its place. The connection still has ONE prepared-statement cache, so two
    threads running the SAME SQL TEXT are handed the SAME `sqlite3_stmt`: one
    binds while the other is mid-step, SQLite returns SQLITE_MISUSE, and
    pysqlite raises `InterfaceError: bad parameter or other API misuse`.

    IT LANDS ON WHICHEVER STATEMENT RUNS MOST OFTEN, which is why it looked like
    two unrelated defects. Found 2026-09-07 in a browser, with tracebacks:

        store.py   meta()       SELECT ... FROM chunk c JOIN doc d ...
        spatial.py _is_place()  SELECT 1 FROM place WHERE norm = ? LIMIT 1

    The first has been reachable since the surface began firing /api/search and
    /api/answer in parallel on 2026-09-04, and survived on timing. The second
    arrived with passage places, which ask that question a few hundred times per
    passage across twenty passages - and that is what took a rare collision to a
    certain one. **A latent concurrency defect is not a rare defect. It is a
    defect waiting for the load that makes it certain.**

    THE LOCK IS HELD ACROSS EXECUTE AND FETCH. Releasing between them leaves the
    statement live and is the same misuse in slower motion. These queries are
    microseconds; the BM25 MATCH is the only slow one, and two concurrent
    searches already contended on it inside SQLite.

    NOT thread-local connections, which was the other candidate: this server
    makes a thread per request, so that means opening and discarding a
    connection per request, and it hides the contention rather than bounding it.
    """

    def __init__(self, db):
        self._db = db
        self._lock = threading.Lock()

    @property
    def row_factory(self):
        return self._db.row_factory

    @row_factory.setter
    def row_factory(self, f):
        self._db.row_factory = f

    def execute(self, sql, params=()):
        with self._lock:
            return _Rows(self._db.execute(sql, params).fetchall())

    def close(self):
        with self._lock:
            self._db.close()


class Store:
    def __init__(self):
        # WRAPPED, NOT BARE. Both are read by every request thread at once; see
        # Shared above for what a bare shared connection does under load.
        self.prov = Shared(sqlite3.connect(
            "file:%s?mode=ro" % PROV_DB.replace("\\", "/"),
            uri=True, check_same_thread=False))
        self.prov.row_factory = sqlite3.Row
        self.bm = Shared(sqlite3.connect(
            "file:%s?mode=ro" % BM25_DB.replace("\\", "/"),
            uri=True, check_same_thread=False))
        self.artifacts = {r["src"]: dict(r) for r in
                          self.prov.execute("SELECT * FROM artifact")}

        # THE BOOK KEY IN A URL IS THE ZIM'S FILENAME STEM, which is what
        # sources.json already records as `kiwix_book`. That is worth a comment
        # only because it was "corrected" to something else on 2026-09-04 and the
        # correction was wrong.
        #
        # kiwix-manage reports a book `name` taken from ZIM metadata -
        # `appropedia_en_all` - and all 25 artifacts here disagree with their
        # filename stem, which made the stems look obviously broken. A live
        # kiwix-serve settled it:
        #
        #     /content/appropedia_en_all              404
        #     /content/appropedia_en_all_maxi_2026-02 200
        #
        # kiwix-serve builds the URL from the FILE PATH. Its own catalogue prints
        # both fields side by side - href="/content/mdwiki_en_all_maxi_2025-11"
        # against <name>mdwiki_en_all</name> - and only the first is a URL.
        #
        # So `kiwix-books.json` records the key a RUNNING server was observed
        # answering to, matched to an artifact by the last path segment. Its
        # absence is not an error; it means nothing has been confirmed, the
        # filename stem is used as a fallback, and the citation is labelled
        # book_verified=false rather than implying a check that never happened.
        self.books = {}
        self.books_from = None
        # THE PATH, NOT THE URL, AND THEY ARE DIFFERENT FIELDS.
        # `books_from` is `verified_against` when present - the SERVER the keys
        # were confirmed against, e.g. http://localhost:8080 - and only falls
        # back to the library path. `unindexed()` needs the FILE, and reading
        # `books_from` for it silently found nothing: os.path.exists() on a URL
        # is False, so 67 books read as zero and the fallback never appeared.
        # Caught by serve.py --selftest, which reports the absence rather than
        # printing a green line about a link it never built.
        self.books_library = None
        self.books_stale = None
        if os.path.exists(BOOKS):
            d = json.load(open(BOOKS, encoding="utf-8"))
            self.books = {int(k): v.get("key") for k, v in d["books"].items()}
            self.books_from = d.get("verified_against") or d.get("from_library")
            self.books_library = d.get("from_library")
            # IS THIS FILE STILL ABOUT THE LIBRARY THAT IS RUNNING?
            # Rebuilding library.xml changes the keys kiwix-serve answers to, and
            # a kiwix-books.json left over from the previous one produces
            # citations that look verified and 404. That happened twice on
            # 2026-09-04, and both times the only symptom was a dead link.
            lib = d.get("from_library")
            if lib and os.path.exists(lib) and d.get("library_mtime"):
                st = os.stat(lib)
                if (int(st.st_mtime) != d["library_mtime"]
                        or st.st_size != d.get("library_size")):
                    self.books_stale = (
                        "%s was rebuilt after these book keys were recorded. Every "
                        "ZIM citation may 404. Re-run: python bin/kiwix-library.py "
                        "--verify-against <kiwix url>" % lib)
        self._terms = None
        self._dense = None
        self._dense_error = None
        self._dense_lock = threading.Lock()
        # The PQ half, loaded under its own lock for the reason the Chroma half
        # has one: ThreadingMixIn means two handler threads can arrive together.
        self._pq = None
        self._pq_error = None
        self._pq_state = None           # absent | stale | ok | error
        self._pq_detail = None
        self._pq_lock = threading.Lock()
        # The mdwiki mirror set is loaded once, lazily, under a lock for the
        # same reason the dense half is: ThreadingMixIn means two handler
        # threads can arrive together, and reading and parsing the same file
        # twice is waste at the exact moment the node is busiest.
        self._mirror = None
        self._mirror_state = None       # ok | absent | stale | unreadable
        self._mirror_detail = None      # one sentence, shown rather than logged
        self._mirror_lock = threading.Lock()
        self._excl_stats = None
        self._unindexed = None

    # ---------------------------------------------------------------- search

    def terms(self, q):
        if self._terms is None:
            self._terms = _load_bin("index-bm25.py").query_terms
        return self._terms(q)

    def _match(self, expr, n):
        try:
            rows = self.bm.execute(
                "SELECT cid FROM chunks WHERE chunks MATCH ? ORDER BY bm25(chunks) LIMIT ?",
                (expr, n)).fetchall()
        except sqlite3.OperationalError as e:
            raise RuntimeError("BM25 query failed: %s" % e)
        return [r[0] for r in rows]

    def place_words(self, q):
        """Which of the query's content words name a place, per the gazetteer.

        LAZY AND OPTIONAL, both deliberately. `spatial` imports this module, so
        importing it at the top would be circular; and §3.4 says nothing gating
        retrieval may require a component that can be absent. No gazetteer, or
        any failure at all, returns the empty set and the caller falls straight
        back to the plain OR query. The gazetteer needs no model - it is one
        SQLite file - so this costs nothing the keyword floor cannot pay.

        IT DELIBERATELY DOES NOT USE `is_place_reference`, WHICH ANSWERS A
        DIFFERENT QUESTION. That test asks *is this question asking about the
        place*, and to keep the spatial card honest it requires a locative
        preposition in front of the name. On `groundwater in Nevada and Utah` it
        accepts Nevada (`prev="in"`) and rejects Utah (`prev="and"`) - correct
        for a card that must not fire on 83,856 real non-spatial questions, and
        wrong here, where the only question is whether a token NAMES a place so
        it can be treated as a qualifier rather than as the subject.

        Using it left `utah` in the topic group, so the scoped query became
        `("groundwater" OR "utah") AND ("nevada")`, which matches the same
        nevada+utah chunks and changed nothing. Measured, not reasoned.

        SO THIS TAKES THE PASSAGE GUARDS WITHOUT THAT BASE: not a free capital,
        `poprank >= PASSAGE_POPRANK` (below it the residue is led by `Valley` and
        `University`, the generic tails of longer proper nouns), and not in
        `AMBIGUOUS`, which is where `turkey`, `nice`, `mobile` and `reading`
        live. A false positive here is cheap - a word becomes a qualifier
        instead of a subject - and if every content word is classified as a
        place the topic group empties and the caller falls back."""
        try:
            import spatial
            if not spatial.available():
                return set()
            out = set()
            for m in spatial.mentions(q):
                if m["clause"]:
                    continue
                if m["poprank"] < spatial.PASSAGE_POPRANK:
                    continue
                if m["text"].lower() in spatial.AMBIGUOUS:
                    continue
                out.update(w for w in m["text"].lower().split() if len(w) > 1)
            return out
        except Exception:                            # noqa: BLE001 - optional
            return set()

    def keyword(self, q, n):
        """The sparse half. Returns chunk ids, best first.

        THIS IS THE SHIPPED PATH AND IT IS THE PLAIN `OR` QUERY. The scoped
        candidate below is NOT on it - see `keyword_scoped`."""
        m = self.terms(q)
        if not m:
            return []
        return self._match(m, n)

    def keyword_scoped(self, q, n):
        """CANDIDATE, NOT SHIPPED. `keyword()` is what the surface calls.

        Topic AND place first, then the plain `OR` query fills the rest, so it
        can only reorder results and never lose them. It exists to fix a real,
        measured defect: `groundwater in Nevada and Utah` returned twelve top
        results containing `groundwater` ZERO times, because in a medical corpus
        `nevada` (1,665 chunks) and `utah` (2,313) are rarer than `groundwater`
        (3,510) and BM25 ranks by rarity. See `query_scoped` in
        bin/index-bm25.py for why counting matched terms does not fix it.

        WHY IT IS NOT SHIPPED: MEASURED AND REJECTED, 2026-09-08.
        Reproduce with `python bin/measure-retrieval.py --scoped`.

        1,079 of the archive's own 83,856 Stack Exchange question titles name a
        place and still have a subject left over. Over 120 of them, sampled with
        a fixed seed:

            slots  topic  place   both
            1200   98.2%  72.7%  70.9%   shipped
            1200  100.0%  98.7%  98.7%   scoped

        and the rule rewrote the page on **91 of 120 queries, 76%**.

        THE DEFECT IT WAS BUILT FOR DOES NOT HAPPEN. `groundwater in Nevada and
        Utah` returns twelve results with `groundwater` nowhere in them, and
        that is genuine - but on those 120 real questions the shipped page
        contained **zero topic terms 0 times and zero place terms 0 times**. The
        98.2% is per-slot noise, not a page that lost its subject. The
        motivating query was one I wrote, not one anyone asked, and it is rarer
        than 1 in 120 in the archive's own questions.

        So the rule rewrites three quarters of place-bearing pages to fix
        something that essentially never occurs, and a rescue-only variant -
        scope only when the plain page has no topic term - would never fire at
        all. The `earthquake building codes in Japan` regression, which promoted
        a US flood timeline over an earthen-building text, is therefore not an
        edge case but the same mechanism working on 76% of queries.

        KEPT RATHER THAN DELETED so the rejection is a command anyone can re-run
        offline instead of a claim in a log, and because the BM25 finding
        underneath it stands: in this corpus `nevada` and `utah` are rarer than
        `groundwater`, so rarity and relevance point in different directions and
        any future ranking work has to start there.

        It lives here rather than in the measurement script so there is ONE copy
        of the rule. A measurement holding its own copy agrees with itself
        forever, which this build has now been bitten by three times."""
        bm25 = _load_bin("index-bm25.py")
        m = bm25.query_terms(q)
        if not m:
            return []

        ids, seen = [], set()
        places = self.place_words(q)
        if places:
            words = bm25.content_words(q)
            topic = [w for w in words if w not in places]
            place = [w for w in words if w in places]
            scoped = bm25.query_scoped(topic, place)
            if scoped:
                for cid in self._match(scoped, n):
                    if cid not in seen:
                        seen.add(cid); ids.append(cid)

        for cid in self._match(m, n):
            if len(ids) >= n:
                break
            if cid not in seen:
                seen.add(cid); ids.append(cid)
        return ids[:n]

    # ------------------------------------------------------------ the PQ half

    def _pq_plan(self):
        """(state, detail, plan) for the PQ index, without importing anything.

        FOUR STATES AND THEY ARE NOT THE SAME FACT, which is the rule this file
        already follows for `unindexed()` and the mirror set. ABSENT is normal -
        the index is new and this node ran without it for two weeks. STALE means
        the vectors on disk are not the ones it was built from, which would
        return citations for the wrong passages, so it is never used.

        The row offsets are derived from the manifest's own stamp rather than
        recomputed from sources.json: the stamp is [slug, rows, bytes] per
        artifact IN BUILD ORDER, which is exactly the cumulative sum needed, and
        deriving them from the same record that is being checked for staleness
        means the two can never disagree."""
        man_p = os.path.join(PQ_DIR, "manifest.json")
        if not os.path.exists(man_p):
            return "absent", "no PQ index; build it with bin/index-pq-build.py", None
        try:
            man = json.load(open(man_p, encoding="utf-8"))
        except Exception as e:                                 # noqa: BLE001
            return "error", "%s is unreadable (%s)" % (man_p, type(e).__name__), None
        ipath = os.path.join(PQ_DIR, man.get("index", ""))
        rpath = os.path.join(PQ_DIR, man.get("rows", "rows.npy"))
        for f in (ipath, rpath):
            if not os.path.exists(f):
                return "absent", "%s names %s and it is not there" % (
                    os.path.basename(man_p), os.path.basename(f)), None

        plan, base, drift = [], 0, []
        for slug, n, size in (man.get("stamp") or {}).get("artifacts", []):
            vf = os.path.join(INDEX, "vectors", slug + ".f16.npy")
            if not os.path.exists(vf):
                drift.append("%s is gone" % slug)
            elif os.path.getsize(vf) != size:
                drift.append("%s is %d bytes, was %d" % (slug, os.path.getsize(vf), size))
            plan.append((slug, int(n), base, vf))
            base += int(n)
        if not plan:
            return "error", "%s carries no artifact stamp" % os.path.basename(man_p), None
        if drift:
            return ("stale",
                    "the vectors changed since this index was built (%s%s). "
                    "Rebuild: python bin/index-pq-build.py"
                    % ("; ".join(drift[:3]), ", and %d more" % (len(drift) - 3)
                       if len(drift) > 3 else ""), None)
        return "ok", None, (man, ipath, rpath, plan, base)

    def _load_pq(self):
        """faiss index + row map + the vector files the rerank scores against.

        NOTHING HERE IS IMPORTED UNTIL A QUERY ASKS FOR IT, same as the Chroma
        half, so a node with no faiss and no numpy still serves keyword search
        and says why rather than failing to start."""
        with self._pq_lock:
            if self._pq is not None or self._pq_error is not None:
                return
            state, detail, plan = self._pq_plan()
            self._pq_state, self._pq_detail = state, detail
            if state != "ok":
                if state in ("stale", "error"):
                    self._pq_error = detail
                return
            man, ipath, rpath, arts, total = plan
            try:
                preimport()          # numpy whole, once - see the note above
                import faiss
                import numpy as np
                from sentence_transformers import SentenceTransformer
                os.environ["HF_HUB_OFFLINE"] = "1"
                os.environ["TRANSFORMERS_OFFLINE"] = "1"
                ix = faiss.read_index(ipath)
                if ix.ntotal != total:
                    self._pq_state = "stale"
                    self._pq_error = self._pq_detail = (
                        "the index holds %s vectors and the row map describes %s - "
                        "refusing to use it, because every citation past the first "
                        "disagreement would name the wrong passage"
                        % ("{:,}".format(ix.ntotal), "{:,}".format(total)))
                    return
                rows = np.load(rpath, mmap_mode="r")
                if rows.shape[0] != total:
                    self._pq_state = "stale"
                    self._pq_error = self._pq_detail = (
                        "rows.npy is %s rows, the index is %s"
                        % ("{:,}".format(rows.shape[0]), "{:,}".format(total)))
                    return
                model = SentenceTransformer(
                    os.path.join(ROOT, "01-models", "tier4-embedding", "bge-m3"),
                    local_files_only=True)
                model.half()
                self._pq = (ix, rows, arts, model, man, total)
                self._pq_state, self._pq_detail = "ok", None
            except Exception as e:                             # noqa: BLE001
                tb = traceback.extract_tb(e.__traceback__)
                where = " <- ".join(
                    "%s:%d %s" % (os.path.basename(f.filename), f.lineno, f.name)
                    for f in tb[-4:])
                self._pq_state = "error"
                self._pq_error = self._pq_detail = "%s: %s [%s]" % (
                    type(e).__name__, e, where)

    def _pq_search(self, q, n, depth):
        """Nominate with PQ, score with the real float16 vectors.

        THE RERANK IS THE WHOLE POINT AND IT IS CHEAP. PQ64 alone is r@5 0.425;
        the same index handing `depth` candidates to an exact inner product over
        vectors/*.npy reaches 0.975, for about 6.6 ms, because `depth` rows of
        2 KB from a memory-mapped array is 400 KB of reads. Anything that skips
        this step is using a much worse index and will not be told so."""
        import numpy as np
        ix, rows, arts, model, _man, total = self._pq
        v = np.asarray(model.encode([q], normalize_embeddings=True), dtype=np.float32)
        _d, cand = ix.search(v, min(depth, total))
        cand = [int(c) for c in cand[0] if c >= 0]
        if not cand:
            return [], {}

        # The real vectors for those rows, looked up by bisect on the artifact
        # bases. A row that cannot be placed RAISES rather than scoring as a
        # zero vector, which would read as orthogonal, sort last, and look like
        # recall lost to quantization. Same reason index-pq-probe.gather() does.
        import bisect
        bases = [a[2] for a in arts]
        M = np.empty((len(cand), v.shape[1]), dtype=np.float32)
        cache = {}
        for pos, g in enumerate(cand):
            ai = bisect.bisect_right(bases, g) - 1
            if ai < 0 or not (arts[ai][2] <= g < arts[ai][2] + arts[ai][1]):
                raise RuntimeError("PQ row %d is outside every artifact" % g)
            mm = cache.get(ai)
            if mm is None:
                mm = cache[ai] = np.load(arts[ai][3], mmap_mode="r")
            M[pos] = np.asarray(mm[g - arts[ai][2]], dtype=np.float32)
        nrm = np.linalg.norm(M, axis=1, keepdims=True)
        nrm[nrm == 0] = 1.0
        score = (M / nrm) @ v[0]

        order = np.argsort(-score)[:n]
        ids, out = [], {}
        for k in order:
            r = rows[cand[int(k)]]
            cid = "%d:%d:%d" % (int(r[0]), int(r[1]), int(r[2]))
            ids.append(cid)
            out[cid] = float(score[int(k)])
        return ids, out

    def pq_state(self):
        """absent | stale | ok | error | None (never asked). Never a bare False."""
        return self._pq_state

    def pq_detail(self):
        return self._pq_detail

    def dense_backend(self):
        """WHICH vector index answered, because they do not cover the same thing.

        PQ64 covers every artifact IT WAS BUILT OVER, which is not the same as
        every artifact in sources.json and stopped being the same on
        2026-09-24: pass 3 added 32,147,292 chunks to a registry the PQ index
        knew nothing about. This sentence said "every artifact in sources.json"
        until then, and it was true the day it was written - which is exactly
        the shape this file keeps catching. `pq_coverage_gap()` is the number.

        Chroma holds only what index-build.py loaded into it, which after the
        2026-09-14 pass is pass 1 alone - 2,315,810 of 6,926,271. Falling back
        from one to the other is a two-thirds loss of dense reach, and a
        fallback nobody can see is the failure NODE-ARCHITECTURE.md lists
        last."""
        if self._pq is not None:
            return "pq"
        if self._dense is not None:
            return "chroma"
        return None

    def dense_coverage(self):
        """Vectors the ACTIVE dense backend can actually reach, or None."""
        if self._pq is not None:
            return self._pq[5]
        if self._dense is not None:
            try:
                return int(self._dense[0].count())
            except Exception:                                  # noqa: BLE001
                return None
        return None

    def pq_coverage_gap(self):
        """What the PQ index holds against what the registry says exists.

        INCOMPLETE IS NOT STALE, AND THE DIFFERENCE IS WHY THIS IS HERE AND NOT
        IN `_pq_plan()`. That function returns `stale` when the vectors on disk
        are not the ones the index was built from, and `_load_pq` then refuses to
        load at all - correctly, because every citation past the first
        disagreement would name the wrong passage. An index built BEFORE a later
        pass has no such fault. It is exactly right about the artifacts it holds
        and merely silent about the ones it does not, so returning `stale` would
        take working dense retrieval over 6.9M chunks away and drop the node to
        keyword-only, which is worse than the problem it fixes.

        So this REPORTS and can never withhold. Nothing in the loading path calls
        it, and it imports nothing.

        IT COMPARES THE MANIFEST AGAINST THE REGISTRY, NOT AGAINST
        `dense_coverage()`, which is None until a query has triggered the lazy
        load - a warning that goes silent exactly when someone looks for it is
        the 2026-09-15 mistake in a new place. And it reads `sources.json` rather
        than `self.artifacts`, for the reason recorded beside SOURCES above.

        (covered, total, [missing files]) or None when there is nothing to
        compare. An empty `missing` is the healthy answer, not the absent one."""
        try:
            man = json.load(open(os.path.join(PQ_DIR, "manifest.json"),
                                 encoding="utf-8"))
            reg = json.load(open(SOURCES, encoding="utf-8"))
        except Exception:                                      # noqa: BLE001
            return None                      # absent or unreadable is not a gap
        if not (man.get("stamp") or {}).get("artifacts"):
            return None
        covered, total, missing = pq_coverage(man, reg)
        return (covered, total, missing) if total else None

    def _load_dense(self):
        """Build the Chroma collection handle and the embedding model, once.

        ONE THREAD LOADS IT. `serve.py`'s Server is socketserver.ThreadingMixIn,
        so two handler threads can arrive here together, and until 2026-09-08
        both of them loaded. chromadb registers a System in a class-level dict
        keyed by the persist directory BEFORE it has finished starting it, so a
        second thread arriving inside that window takes a System whose Rust
        bindings do not exist yet. Measured on the node, 8 threads x 12 cold
        starts: 2 failures of 96, `ValueError: Could not connect to tenant
        default_tenant` raised over `AttributeError: 'RustBindingsAPI' object
        has no attribute 'bindings'`. The same window is where the
        `KeyError: '<persist dir>'` seen in service comes from - the same dict,
        a different loser.

        A 2-in-96 race that cost one query would be a nuisance. This one cost
        every query: `_dense_error` is sticky by design, so a single unlucky
        cold start left the process keyword-only until restart with a 27 GB
        vector store on the drive in perfect condition, reporting a message
        whose entire text was a path. That is why this node had never returned
        a dense hit.

        The lock also stops two threads each loading a separate copy of bge-m3,
        which was wasteful before it was ever a crash."""
        with self._dense_lock:
            if self._dense is not None or self._dense_error is not None:
                return                       # another thread did it while we waited
            try:
                preimport()          # same shared lock as the PQ loader
                import chromadb
                from sentence_transformers import SentenceTransformer
                os.environ["HF_HUB_OFFLINE"] = "1"
                os.environ["TRANSFORMERS_OFFLINE"] = "1"
                client = chromadb.PersistentClient(path=os.path.join(INDEX, "chroma"))
                col = client.get_collection("ark_pass1")
                model = SentenceTransformer(
                    os.path.join(ROOT, "01-models", "tier4-embedding", "bge-m3"),
                    local_files_only=True)
                model.half()
                self._dense = (col, model)
            except Exception as e:                 # noqa: BLE001 - reported, not raised
                # NAME THE LINE, NOT JUST THE TYPE. This reported
                # `KeyError: '<root>\\10-index\\chroma'` for two days: a
                # message that is entirely a path, because str() on a KeyError IS
                # the key and carries no location. Keeping the last frames is what
                # turns "it failed" into "it failed HERE".
                tb = traceback.extract_tb(e.__traceback__)
                where = " <- ".join(
                    "%s:%d %s" % (os.path.basename(f.filename), f.lineno, f.name)
                    for f in tb[-4:])
                self._dense_error = "%s: %s [%s]" % (type(e).__name__, e, where)

    def dense(self, q, n):
        """The vector half, loaded only when asked for. Returns (ids, {id: score})
        or ([], {}) with `dense_available()` False if the stack is not installed."""
        # PQ FIRST, CHROMA AS A NAMED FALLBACK. Not silently: dense_backend()
        # and dense_coverage() say which one answered and over how many vectors,
        # because the two do not cover the same corpus.
        if self._pq is None and self._pq_error is None and self._pq_state is None:
            self._load_pq()
        if self._pq is not None:
            return self._pq_search(q, n, RERANK_DEPTH)
        if self._dense is None and self._dense_error is None:
            self._load_dense()               # cheap check first, lock only on the miss
        if self._dense is None:
            return [], {}
        col, model = self._dense
        v = model.encode([q], normalize_embeddings=True)
        r = col.query(query_embeddings=v.tolist(), n_results=n)
        ids = list(r["ids"][0])
        return ids, {c: 1.0 - d for c, d in zip(ids, r["distances"][0])}

    def dense_available(self):
        return self._pq is not None or self._dense is not None

    def dense_attempted(self):
        """Has the stack ever been asked for?

        NOT LOADED AND FAILED TO LOAD ARE DIFFERENT FACTS. The vector half is
        lazy: nothing is imported until the first hybrid or dense query. Health
        reported `dense_search: false, dense_error: null` and listed it under
        `degraded`, which reads as a fault, on a server that had simply never
        been asked a hybrid question. On 2026-09-06 that cost an hour of
        suspecting the vector store during an actual Chroma segfault - the one
        moment a false alarm was most expensive."""
        return (self._dense is not None or self._dense_error is not None
                or self._pq is not None or self._pq_error is not None)

    def dense_error(self):
        """The error of whichever half is actually blocking a dense answer.

        A PQ index that is merely ABSENT is not an error - this node ran without
        one until 2026-09-15 - so it does not mask a real Chroma failure."""
        if self._pq is None and self._pq_error:
            return "pq: %s" % self._pq_error
        return self._dense_error

    @staticmethod
    def fuse(dense_ids, sparse_ids):
        """Reciprocal Rank Fusion, k=60. Rank only, never score: cosine similarity
        is 0..1 and BM25 is unbounded and negative, so the two are not comparable
        as numbers. Same constant and same reasoning as bin/index-query.py."""
        score = {}
        for ids in (dense_ids, sparse_ids):
            for rank, cid in enumerate(ids):
                score[cid] = score.get(cid, 0.0) + 1.0 / (RRF_K + rank + 1)
        return sorted(score, key=lambda c: -score[c])

    @staticmethod
    def agreement(n_both):
        """Reported, not hidden. Thresholds and wording from bin/index-query.py,
        which derived them from the five acceptance questions on 2026-09-03. It is
        a pattern from five questions, not a law, and it is labelled as one."""
        if n_both == 0:
            return ("low", "the two retrievers found nothing in common - treat this "
                           "ordering as arbitrary and read the passages, not the ranks")
        if n_both <= 2:
            return ("weak", "one retriever is carrying this result")
        return ("good", "")

    # ------------------------------------------------------------ provenance

    def meta(self, cid):
        r = self.prov.execute(
            "SELECT c.cid, c.src, c.dnum, c.i, c.n, c.page, c.off, c.len,"
            "       d.path, d.title, d.kind "
            "FROM chunk c JOIN doc d ON d.src=c.src AND d.dnum=c.dnum "
            "WHERE c.cid=?", (cid,)).fetchone()
        return dict(r) if r else None

    def text(self, m):
        """The passage itself: one seek and one readline into the jsonl that
        already holds it. The text is not duplicated anywhere - provenance.sqlite3
        stores a pointer to it, which is why it is 146 MB rather than 3.4 GB."""
        a = self.artifacts[m["src"]]
        p = os.path.join(CHUNKS, a["jsonl"])
        with open(p, "rb") as fh:
            fh.seek(m["off"])
            raw = fh.read(m["len"])
        row = json.loads(raw)
        if row.get("id") != m["cid"]:
            raise RuntimeError(
                "provenance points at %r but the jsonl line is %r - the index was "
                "rebuilt without rebuilding provenance.sqlite3"
                % (m["cid"], row.get("id")))
        return row.get("text", "")

    def citation(self, m):
        """chunk -> artifact -> a URL an operator can open.

        Two shapes, because the archive has two. Twenty-five artifacts are ZIMs
        served by kiwix-serve; four are folders of PDFs that nothing serves, so
        ark-api serves them itself under /files/ and appends the page anchor every
        PDF reader understands."""
        a = self.artifacts[m["src"]]
        out = {
            "artifact": a["file"],
            "shelf": a["shelf"],
            "lang": a["lang"],
            "sha256": a["sha256"],
            "title": m["title"] or m["path"],
            "path": m["path"],
            "chunk": "%d/%d" % (m["i"] + 1, m["n"]),
        }
        if a["kiwix_book"]:
            # THE OBSERVED KEY WINS. a["kiwix_book"] is the filename stem, which
            # is what kiwix-serve 3.8.2 answers to and is NOT what 3.8.1 answers
            # to - 3.8.1 keeps the directory, serving
            # /content/07-corpora-supplemental/mdwiki_en_all_maxi_2025-11. Both
            # were observed against the same library.xml on 2026-09-04. The key is
            # the stored path minus the extension; how much of the path survives
            # is a property of the binary, so it is read from the running server
            # and never constructed here.
            key = self.books.get(m["src"]) or a["kiwix_book"]
            # safe="/" - a key can contain a separator and it must stay one. With
            # safe="" the 3.8.1 form becomes 07-corpora-supplemental%2Fmdwiki...
            # and 404s.
            book = urllib.parse.quote(key, safe="/")
            path = _quasi(m["path"])
            out["kind"] = "zim"
            out["kiwix_book"] = key
            # true only when a running kiwix-serve was asked and answered. Not a
            # claim about the URL being correct - a claim about it having been
            # checked, which is a different and smaller thing.
            out["book_verified"] = m["src"] in self.books
            out["url"] = "%s/viewer#%s/%s" % (KIWIX, book, path)
            out["raw_url"] = "%s/content/%s/%s" % (KIWIX, book, path)
        else:
            out["kind"] = "pdf"
            out["page"] = m["page"]
            rel = "%s/%s" % (a["shelf"], m["path"])
            out["url"] = "/files/%s#page=%s" % (_quasi(rel), m["page"] or 1)
            out["raw_url"] = "/files/%s" % _quasi(rel)
        return out

    def file_path(self, rel):
        """Resolve a /files/ request, refusing anything that escapes the archive.
        The node has one user and no auth by design (§7, 'multi-user accounts and
        permissions' is on the do-not-build list). That is not a reason to serve
        C:\\Windows to whoever is on the WiFi."""
        base = os.path.realpath(ROOT)
        full = os.path.realpath(os.path.join(base, rel.replace("/", os.sep)))
        if not full.startswith(base + os.sep):      # the base itself is a folder
            return None
        return full if os.path.isfile(full) else None

    # ------------------------------------------------------------- filtering

    _NAV_TITLE = re.compile(r"^(category|categoría|tag|tags|index|contents|"
                            r"table of contents|all pages)\b", re.I)

    def is_navigation(self, m, txt):
        """Tag listings and tables of contents match many words and answer nothing.
        Suppressed at query time, never deleted - the same call DECISIONS.md
        records on 2026-09-03, for the same reason: it is reversible."""
        t = (m.get("title") or "")
        if self._NAV_TITLE.match(t):
            return True
        if m.get("path", "").startswith(("Category:", "Tag/", "Special:")):
            return True
        words = txt.split()
        if len(words) > 40:
            uniq = len(set(w.lower() for w in words))
            if uniq / float(len(words)) < 0.35:
                return True
        return False

    # --------------------------------------------------- index quality filters
    #
    # THREE RULES, ONE MECHANISM, AND 37.1% OF THE INDEX.
    # Measured 2026-09-11 over all 942,032 documents, not sampled:
    #
    #     iFixit user profile pages   297,242 docs   298,218 chunks   12.88%
    #     wikem translations          89,615 docs    269,471 chunks   11.64%
    #     mdwiki articles wikipedia
    #       en_medicine also carries  69,980 docs    291,177 chunks   12.57%
    #     ----------------------------------------------------------------
    #                                                858,866 chunks   37.11%
    #
    # so 2,315,810 chunks become 1,456,944. Every one of those is a user
    # directory, a translation of something already here, or a second copy of an
    # article this archive holds at a NEWER revision.
    #
    # SUPPRESSED AT QUERY TIME, NEVER DELETED - the same call DECISIONS.md
    # records for `is_navigation` on 2026-09-03, for the same reason: it is
    # reversible, it needs no re-embedding, and the chunks stay in the index
    # where a later decision can bring them back. `ARK_NO_FILTERS=1` turns all
    # three off in one place so a measurement can compare with and without,
    # rather than against a claim in a log.
    #
    # THE RULES KEY ON THE ARTIFACT FILENAME, NOT ON `src`. The src integers are
    # an artifact of index build order and would silently point at the wrong
    # corpus after a rebuild; the filename prefix is what the operator reads in
    # a citation.
    #
    # WHY EACH ONE.
    #
    # 1. iFixit `User/`. 12.9% of the index is *"Albert Einstein @albert_e
    #    1 Reputation 21/01/17"*, which is why asking who Albert Einstein was
    #    returned three accounts. **Not a ranking failure** - BM25 is correct
    #    over a corpus where the commonest thing containing a person's name is a
    #    list of people with that name. The Guides, Devices and Teardowns, which
    #    are why this artifact is here at all, are untouched.
    #
    #    AND THE PREDICATE IS NOT THE ONE DECISIONS.MD WROTE DOWN. That entry
    #    says *"`doc.path` carries `/User/`, so exclusion is deterministic"*.
    #    Literally applied, `'%/User/%'` matches **67 documents** of 297,242:
    #    the paths start `User/1098034/...` and only 67 stray rows in the
    #    Spanish artifact carry a full URL. A filter written from that sentence
    #    would have removed 67 rows and been reported as done - the same shape
    #    as every defect this build recorded in the last two days. Both forms
    #    are matched here.
    #
    # 2. wikem translations. 96.4% of that artifact is per-language subpages of
    #    its own 3.3% English. An English dosing question returned `Advil/vi`,
    #    `Advil/pl` and `Advil/ru`, and §9.2 tells the operator to read the
    #    source passage - four of five in languages they do not read makes a
    #    safety rule unfollowable, which is worse than an unhelpful result.
    #
    #    `es` IS KEPT. This build is deliberately bilingual and Spanish is 7.2%
    #    of that artifact; a filter that kept only English would delete a
    #    first-class language. Juan's decision, 2026-09-11.
    #
    #    THE DROPPED LANGUAGES ARE NAMED RATHER THAN MATCHED BY SHAPE. A regex
    #    for *any* two-letter final segment would also eat a real article whose
    #    title ends that way, and the copy-pairs matcher in `bin/copy-pairs.sh`
    #    already states the principle this build follows: a pattern that does
    #    not understand something fails to match, so the item is SHOWN rather
    #    than hidden. That is the safe direction to be wrong in. The cost is
    #    that a language appearing in a future wikem snapshot is kept until
    #    this list is updated, which is visible rather than silent.
    #
    # 3. mdwiki mirror. 97.7% of mdwiki's articles are also in
    #    `wikipedia_en_medicine_maxi`, and 97.0% of its chunks. Sampling 200 of
    #    those articles and comparing the full document text: **52% are
    #    byte-identical, 30% are >=0.90 similar, 18% are a different revision.**
    #    The byte-identical half is already caught by the `duplicate_text`
    #    suppressor in serve.search - but only AFTER it has taken a slot in the
    #    candidate pool. The other half is not caught by anything, because two
    #    revisions of one article are not byte-identical.
    #
    #    THE RULE WAS "SAME PATH" FOR ONE DAY AND IT WAS WRONG. Twenty of the
    #    differing pairs were read by hand on 2026-09-11 with
    #    `bin/compare-revisions.py`, and the reading reversed the design.
    #
    #    **mdwiki is not an old copy of Wikipedia.** It is WikiProject
    #    Medicine's offline build, and its articles carry a structured clinical
    #    infobox - symptoms, causes, risk factors, diagnostic method,
    #    differential diagnosis, treatment, prognosis, frequency, main uses,
    #    typical dose - that the 2026-04 Wikipedia articles have in many cases
    #    collapsed to a single `Specialty:` line. Eight of the twenty carried
    #    something actionable the newer article had lost:
    #
    #        Fixed_drug_reaction           5,179 chars -> 1,079; the new one has
    #                                      no treatment, diagnosis or DDx at all
    #        Transfusion-dependent_anemia  "restrictive threshold 7 to 8 g/dL,
    #                                      liberal 9 to 10" became "a range
    #                                      between 6 and 10 may be considered"
    #        Tafamidis                     20 to 80 mg once daily -> no dose
    #        Risankizumab                  150 mg at week 0, 4, then q12w -> none
    #        Baylisascaris_procyonis       "20% bleach (1% sodium hypochlorite)"
    #                                      -> sentence kept, concentration gone
    #        Carcinoid, Atrial_septal_defect, Mansonelliasis
    #                                      infobox -> `Specialty:` only
    #
    #    and five were clearly better in Wikipedia, on CURRENCY of indications:
    #    Risankizumab gained Crohn's and ulcerative colitis, Oxaliplatin gained
    #    pancreatic and gastric and the CAPOX regimen, Dubin-Johnson gained a
    #    histology section.
    #
    #    **So neither side wins, and that is the finding.** Wikipedia is more
    #    current on what a drug is approved for; mdwiki is more complete on how
    #    much to give. Suppressing an identical copy removes noise; suppressing
    #    a differing revision hides a dose. Juan's rule for this node already
    #    decides that case - *more info is better, trust the operator* - so the
    #    rule was narrowed from *same path* to **same path AND near-verbatim
    #    containment**, 2026-09-12.
    #
    #    THE SET IS GENERATED, NOT DERIVED HERE, AND LENGTH IS WHY.
    #    `Atrial_septal_defect` is 30,236 characters against 31,290, a 3%
    #    difference, at difflib similarity **0.062** - the same prose in a
    #    different section order. Nothing in provenance.sqlite3 separates that
    #    from a real copy, so the comparison needs both .jsonl files, about
    #    1.1 GB, and runs offline: `python bin/index-mirror-set.py` writes
    #    `10-index/mirror-mdwiki.json`. See that file for the metric, which is
    #    asymmetric containment rather than similarity, and for what its
    #    threshold means measured against synthetic articles.
    #
    #    AND A GENERATED FILE THAT CAN GO STALE IS THE ONE THING THIS LAYER HAS
    #    ALREADY BEEN BITTEN BY. `kiwix-books.json` left over from a previous
    #    `library.xml` produced citations that looked verified and 404'd, twice
    #    on 2026-09-04, and the only symptom was a dead link. So the set carries
    #    the size and mtime of both .jsonl files and of provenance.sqlite3, and
    #    a mismatch DISABLES the rule and is reported - it never filters on a
    #    set that describes a different index.
    #
    #    MDWIKI IS NOT DROPPED. It carries 1,659 articles wikipedia_en_medicine
    #    does not - `Enoxaparin`, `Cisatracurium`, `Shingles_vaccine`,
    #    `Elbow_dislocation`, `Neonatal_herpes_simplex` - which are drugs and
    #    procedures, not filler.
    #
    #    THE 1,659 IS AN OVERCOUNT AND THIS IS THE KNOWN HOLE. Path intersection
    #    cannot see a rename or a redirect, and Wikipedia having no page at the
    #    exact path `Enoxaparin` almost certainly means it has one elsewhere. So
    #    this rule keeps some duplicates it believes are unique. Stated rather
    #    than hidden; title matching would catch most of the rest.

    EXCLUDE_OFF = os.environ.get("ARK_NO_FILTERS") == "1"

    # Every language subpage wikem carries except `es`. Counts are that artifact's
    # own, measured 2026-09-11 over its 101,382 documents.
    WIKEM_DROP = {
        "ar": 4455, "de": 7047, "fr": 7063, "hi": 1224, "id": 7092, "it": 7113,
        "ja": 7101, "ko": 7147, "pl": 6895, "pt": 7103, "ru": 7062, "tr": 7056,
        "vi": 7151, "zh": 6106,
    }
    WIKEM_KEEP = ("es",)

    EXCLUDE_WHY = {
        "user_profile": "an iFixit contributor profile, not repair content",
        "translation": "a wikem translation of an English page this archive holds",
        "mirror": "also in wikipedia_en_medicine_maxi, at a newer revision",
    }

    def _src_of(self, prefix):
        """The src of the one artifact whose filename starts with `prefix`.

        None when the artifact is absent, which is not an error: a node built
        from a partial archive simply has nothing for that rule to exclude."""
        for src, a in self.artifacts.items():
            if a["file"].startswith(prefix):
                return src
        return None

    def _load_mirror(self):
        """Read `10-index/mirror-mdwiki.json` and decide whether to trust it.

        RETURNS (dnums, state, detail) AND NEVER RAISES. Every failure here -
        the file absent, unreadable, or describing a different index - produces
        an EMPTY set, which means the mirror rule does not fire and both copies
        are shown. Failing toward showing is the safe direction, and it is the
        same call `bin/copy-pairs.sh` records for a pattern its matcher does not
        understand.

        THE STAMP IS CHECKED BEFORE THE CONTENT IS USED. The dnums belong to a
        particular provenance.sqlite3 and the comparison to a particular pair of
        .jsonl files; if any of the three has changed, those integers point at
        documents nobody compared. `kiwix-books.json` is the precedent and the
        warning: a stale generated file there produced citations that looked
        verified and 404'd, and the only symptom was a dead link."""
        # NO PAIR, NOTHING TO COMPARE, AND NOTHING DEGRADED. The starter kit has
        # neither mdwiki nor wikipedia_en_medicine, and on the 2026-10-03
        # new-account test /api/health listed the missing set as degraded on a
        # correct install. The set only means something when both are indexed.
        if self._src_of("mdwiki_") is None or \
                self._src_of("wikipedia_en_medicine") is None:
            return frozenset(), "not_needed", None
        if not os.path.exists(MIRROR_SET):
            return frozenset(), "absent", (
                "%s has not been built, so mdwiki and wikipedia_en_medicine are "
                "both searched and duplicate articles can appear. Build it: "
                "python bin/index-mirror-set.py" % os.path.basename(MIRROR_SET))
        try:
            d = json.load(open(MIRROR_SET, encoding="utf-8"))
            want = d["stamp"]
            here = {
                "old_jsonl": os.path.join(CHUNKS, d["old"]["jsonl"]),
                "new_jsonl": os.path.join(CHUNKS, d["new"]["jsonl"]),
                "provenance": PROV_DB,
            }
            for key, path in here.items():
                w = want[key]
                if not os.path.exists(path):
                    return frozenset(), "stale", (
                        "%s names %s, which is not on this drive. The mirror "
                        "rule is OFF. Rebuild: python bin/index-mirror-set.py"
                        % (os.path.basename(MIRROR_SET), os.path.basename(path)))
                st = os.stat(path)
                if st.st_size != w["size"] or int(st.st_mtime) != w["mtime"]:
                    return frozenset(), "stale", (
                        "%s was built against a different %s (%s bytes then, %s "
                        "now). The mirror rule is OFF rather than filtering on a "
                        "set that describes another index. Rebuild: python "
                        "bin/index-mirror-set.py"
                        % (os.path.basename(MIRROR_SET), os.path.basename(path),
                           "{:,}".format(w["size"]), "{:,}".format(st.st_size)))
            return (frozenset(d["dnums"]), "ok",
                    "built %s at threshold %.3f, %s of %s shared articles"
                    % (d.get("generated", "?"), d.get("threshold", 0),
                       "{:,}".format(len(d["dnums"])),
                       "{:,}".format(d.get("shared", 0))))
        except Exception as e:                   # noqa: BLE001 - reported, not raised
            return frozenset(), "unreadable", (
                "%s could not be read (%s: %s). The mirror rule is OFF. Rebuild: "
                "python bin/index-mirror-set.py"
                % (os.path.basename(MIRROR_SET), type(e).__name__, e))

    def _mirrored_dnums(self):
        """mdwiki documents the Wikipedia article at the same path already
        contains. Loaded once, lazily, under a lock."""
        if self._mirror is not None:
            return self._mirror
        with self._mirror_lock:
            if self._mirror is not None:
                return self._mirror
            dup, self._mirror_state, self._mirror_detail = self._load_mirror()
            self._mirror = frozenset(dup)
            return self._mirror

    def excluded(self, m):
        """Why this passage is not shown, or None to show it.

        CALLED BEFORE `text()`, DELIBERATELY. Roughly one retrieved candidate in
        three is excluded, and each one that reaches `text()` costs a seek and a
        read into a half-gigabyte jsonl for a passage nobody will see."""
        if self.EXCLUDE_OFF:
            return None
        a = self.artifacts.get(m["src"])
        if not a:
            return None
        f, p = a["file"], (m.get("path") or "")
        if f.startswith("ifixit_"):
            # both spellings; see the note above on what the one-line rule in
            # DECISIONS.md would actually have matched
            if p.startswith("User/") or "/User/" in p:
                return "user_profile"
        elif f.startswith("wikem_"):
            seg = p.rsplit("/", 1)
            if len(seg) == 2 and seg[1] in self.WIKEM_DROP:
                return "translation"
        elif f.startswith("mdwiki_"):
            if m["dnum"] in self._mirrored_dnums():
                return "mirror"
        return None

    def exclusion_stats(self):
        """How many chunks each rule removes, counted rather than remembered.

        COUNTED, NOT COPIED FROM THE COMMENT ABOVE. The figures in this module's
        header were measured once; these are read off the index the node is
        actually serving, so a rebuilt or partial index reports itself instead of
        repeating a number from September.

        ABOUT 1.2 SECONDS, AND THE FIRST SHAPE TOOK TEN. The mirror rule began as
        78 batched `dnum IN (...)` counts, each of which is a full scan of a
        2.3M-row table - the index on `chunk` is its cid primary key and nothing
        else, so there is no cheap way to ask for a set of dnums. Reading each
        mdwiki document's `n` once (`i=0` is the first chunk of every document
        and `n` is how many that document has) turns 78 scans into one.
        Cached after the first call; health and --selftest both ask."""
        if self._excl_stats is not None:
            return self._excl_stats
        out = {}
        ifx = [s for s, a in self.artifacts.items() if a["file"].startswith("ifixit_")]
        wkm, mdw = self._src_of("wikem_"), self._src_of("mdwiki_")
        def cnt(where, params):
            return self.prov.execute(
                "SELECT COUNT(*) FROM chunk k JOIN doc d ON d.src=k.src AND "
                "d.dnum=k.dnum WHERE %s" % where, params).fetchone()[0]
        if ifx:
            out["user_profile"] = cnt(
                "k.src IN (%s) AND (d.path LIKE 'User/%%' OR d.path LIKE '%%/User/%%')"
                % ",".join("?" * len(ifx)), ifx)
        if wkm is not None:
            langs = sorted(self.WIKEM_DROP)
            out["translation"] = cnt(
                "k.src=? AND (%s)" % " OR ".join(["d.path LIKE ?"] * len(langs)),
                [wkm] + ["%/" + L for L in langs])
        if mdw is not None:
            dup = self._mirrored_dnums()
            # An empty set means the rule is not firing - no set file, or a
            # stale one - and scanning 300,100 chunks to add up zero is waste on
            # exactly the node that is already degraded.
            out["mirror"] = sum(
                r[1] for r in self.prov.execute(
                    "SELECT dnum, n FROM chunk WHERE src=? AND i=0", (mdw,)).fetchall()
                if r[0] in dup) if dup else 0
        self._mirrored_dnums()               # so the state below is populated
        self._excl_stats = {"by_rule": out, "chunks": sum(out.values()),
                            "off": self.EXCLUDE_OFF,
                            # A MIRROR COUNT OF ZERO HAS TWO MEANINGS and they
                            # are opposite: the artifacts are absent, or the set
                            # is stale and the rule was switched off to avoid
                            # filtering on it. Reported so the health line and
                            # --selftest can say which.
                            "mirror_state": self._mirror_state,
                            "mirror_detail": self._mirror_detail}
        return self._excl_stats

    # ------------------------------------------------- what is served, unsearched
    #
    # THE NODE HAS BEEN SAYING "NOT IN ARCHIVE" WHEN IT MEANT "NOT IN THE INDEX",
    # and until 2026-09-12 there was nothing to offer instead. `library.xml` held
    # 25 books, all in one directory, so 42 artifacts and 686 GB - Wikipedia EN
    # and ES, Stack Overflow, Gutenberg, Wiktionary - could not be reached by the
    # running node by ANY route: not searched, not linked, not browsable. Being
    # unindexed and being unserved are different faults and they had one cause.
    #
    # They do not any more. kiwix-serve holds all 67, so the honest sentence can
    # end in a door rather than an apology.
    #
    # A LINK, NOT A MERGE, AND THE REASON IS §9.2. A Kiwix full-text hit has no
    # chunk, no provenance row and no byte offset, so it cannot carry a citation
    # the way every result in the sources pane does. Folding those hits in beside
    # cited ones would make the GROUNDED badge mean two different things on one
    # screen, which is the defect this build spent 09-09 to 09-11 removing from
    # the answer pane. So the operator is handed a real search over 686 GB and
    # the citation contract is left intact.

    # THE SEARCH FORM, MEASURED 2026-09-12 AGAINST THE RUNNING SERVER, and it
    # took four tries because the first three were written from memory.
    #
    #     /search?pattern=X                          400  Invalid request
    #     /search?books.filter.lang=&pattern=X       400  what shipped first
    #     /search?books.filter.lang=eng,spa&...      400
    #     /search?books.filter.lang=mul&...          400
    #     /search?books.filter.lang=eng&pattern=X    200
    #
    # kiwix-serve 3.8.1 REQUIRES a book filter and the only one that works is a
    # single language. `bin/kiwix-search-form.py` reproduces this.
    #
    # AND THE REPEATED PARAMETER IS A TRAP. `books.filter.lang=eng&books.filter
    # .lang=spa` answers **200**, which is why it was nearly shipped - but
    # mapping every result back to its book showed it reaching `eng:3` for
    # `agua`, identical to `eng` alone, while `lang=spa` alone reaches `spa:5`
    # including wikipedia_es_all_maxi. The second value is discarded. A 200 is
    # not coverage, and the third time that distinction mattered in one day.
    #
    # SO: ONE LINK PER LANGUAGE. This archive is deliberately bilingual - 9 of
    # its 67 books are Spanish and one of the five acceptance questions is in
    # Spanish - and a single link carrying `lang=eng` would silently hide every
    # Spanish book on the drive. That is the wikem translation defect arriving
    # from the opposite direction: an operator shown only what someone else can
    # read. Two links is less tidy and it is the honest shape.
    KIWIX_SEARCH = "%s/search?books.filter.lang=%s&pattern=%s"

    # Enough to label a link. Unknown codes show the raw code rather than
    # guessing at a name, which is how `lang` became a badge that lied on
    # 2026-09-10.
    LANG_NAMES = {"eng": "English", "spa": "espanol", "fra": "francais",
                  "por": "portugues", "deu": "Deutsch"}

    def unindexed(self, query=None):
        """What kiwix-serve holds that retrieval does not cover.

        READ FROM THE LIBRARY THE SERVER WAS STARTED WITH, not from a count
        written down here. `kiwix-books.json` records which library it was
        confirmed against and store already checks that stamp for staleness, so
        this reuses it: if the two have drifted, `books_stale` is already saying
        so and this returns nothing rather than describing a library nobody is
        serving."""
        if self._unindexed is None:
            # A ZERO HERE HAS FOUR CAUSES AND THEY ARE NOT THE SAME FACT.
            # The first version returned 0 for all of them and the selftest line
            # read "nothing served beyond the index, OR the library stamp is
            # stale" - which is where a real bug hid: books_from is the server
            # URL, not the library path, so os.path.exists() was False and 67
            # books read as none. Same shape as `mirror: 0` meaning both "the
            # artifacts are absent" and "the rule was switched off", which this
            # build named and fixed on 09-12 four hours earlier.
            served, shelves, langs, state = [], {}, {}, "ok"
            lib = self.books_library
            if not lib:
                state = ("no library recorded - %s is missing or was never "
                         "confirmed against a running kiwix-serve. Run: python "
                         "bin/kiwix-library.py --verify-against %s"
                         % (os.path.basename(BOOKS), KIWIX))
            elif self.books_stale:
                state = "the library stamp is stale, so what is served is unknown"
            elif not os.path.exists(lib):
                state = "%s is recorded as the library and is not on this drive" % lib
            else:
                try:
                    for b in ET.parse(lib).getroot().findall("book"):
                        p = (b.get("path") or "").replace("\\", "/")
                        stem = re.sub(r"\.zim$", "", os.path.basename(p), flags=re.I)
                        if not stem:
                            continue
                        served.append(stem)
                        langs[stem] = (b.get("language") or "").split(",")[0].strip()
                        shelves.setdefault(p.rsplit("/", 2)[-2] if "/" in p
                                           else "", []).append(stem)
                except Exception as e:           # noqa: BLE001 - reported, not raised
                    served, shelves, langs = [], {}, {}
                    state = "%s could not be parsed (%s)" % (lib, type(e).__name__)
            mine = {a["kiwix_book"] for a in self.artifacts.values()
                    if a.get("kiwix_book")}
            extra = sorted(set(served) - mine)
            if state == "ok" and not extra:
                state = "every served book is in the index"
            self._unindexed = {
                "served": len(served),
                "indexed": len(mine),
                "extra": len(extra),
                "state": state,
                "library": lib,
                "shelves": sorted(s for s in shelves if s),
                # named rather than counted: "42 more artifacts" is not a fact an
                # operator can act on, and these are the ones they would want
                "notable": [s for s in extra if s.split("_")[0] in
                            ("wikipedia", "stackoverflow.com", "gutenberg",
                             "wiktionary", "wikisource", "khanacademy")][:6],
                # COUNTED OVER THE UNINDEXED SET, not over the whole library.
                # The link says what it will reach, and what it reaches is the
                # books this node cannot search - not all 67.
                "by_lang": sorted(
                    ((lg, sum(1 for st in extra if langs.get(st) == lg))
                     for lg in sorted(set(langs.get(st, "") for st in extra))
                     if lg),
                    key=lambda kv: -kv[1]),
            }
        out = dict(self._unindexed)
        if query and out["extra"]:
            q = urllib.parse.quote(query, safe="")
            out["search_urls"] = [
                {"lang": lg, "label": self.LANG_NAMES.get(lg, lg), "books": n,
                 "url": self.KIWIX_SEARCH % (KIWIX, lg, q)}
                for lg, n in out["by_lang"]]
        return out

    def stats(self):
        nc = self.prov.execute("SELECT COUNT(*) FROM chunk").fetchone()[0]
        nd = self.prov.execute("SELECT COUNT(*) FROM doc").fetchone()[0]
        zims = sum(1 for a in self.artifacts.values() if a["kiwix_book"])
        ex = self.exclusion_stats()
        return {"artifacts": len(self.artifacts), "documents": nd, "chunks": nc,
                # WHAT IS IN THE INDEX AND WHAT THE NODE WILL SHOW YOU ARE NOW
                # TWO DIFFERENT NUMBERS, so both are reported. A node quietly
                # answering from 63% of its own index while printing the whole
                # figure would be the §11.2 shape in the health line.
                "chunks_searchable": nc - ex["chunks"],
                "excluded": ex,
                "zim_artifacts": zims,
                "confirmed_book_keys": len(self.books),
                "confirmed_against": self.books_from,
                "book_keys_stale": self.books_stale,
                # SERVED AND SEARCHED ARE NOW DIFFERENT NUMBERS TOO, and this is
                # the second place in one health payload where that distinction
                # had to be made explicit. 67 books are reachable; 25 of them can
                # be cited.
                "unindexed": self.unindexed()}


def pq_coverage(man, registry):
    """(covered, total, [missing files]) from two records, with no IO.

    Pure on purpose: `selftest()` exercises it with dictionaries and needs
    neither a manifest nor a registry on disk, the same reason `excluded()`\'s
    fixtures are synthetic paths.

    An artifact the MANIFEST holds and the registry does not is ignored rather
    than counted. That direction is drift, `_pq_plan()` already detects it by
    file size, and a coverage number is not the place to report it twice."""
    stamped = {slug for slug, _n, _bytes in
               (man.get("stamp") or {}).get("artifacts", [])}
    covered = total = 0
    missing = []
    for a in (registry.get("artifacts") or {}).values():
        n = int(a.get("chunks") or 0)
        total += n
        if a.get("file") in stamped:
            covered += n
        elif a.get("file"):
            missing.append(a["file"])
    return covered, total, sorted(missing)


# --------------------------------------------------------------------- selftest

def selftest():
    """The index quality filters, against synthetic artifacts and paths.

    NO DATABASE, NO INDEX, NO MODEL - the same shape as `bin/ark.py selftest`
    and for the same reason: a check that needs a 52 GB index and a loaded
    embedding model is a check nobody runs, and §8.10 says a second person must
    be able to rebuild this machine from printed instructions and find out
    whether it works. The fixtures are REAL PATHS taken from provenance.sqlite3
    on 2026-09-11, including the three that broke the rule as first written.

    What it cannot prove is written beside the green line: that the filters
    remove the number of chunks this module's comment claims. Only
    `serve.py --selftest` on the real index shows that, and it asserts it.
    """
    _MIRROR_SET_REAL = MIRROR_SET       # restored in the finally below
    s = Store.__new__(Store)
    s.artifacts = {
        1: {"file": "mdwiki_en_all_maxi_2025-11.zim"},
        2: {"file": "wikipedia_en_medicine_maxi_2026-04.zim"},
        4: {"file": "wikem_en_all_maxi_2026-07.zim"},
        8: {"file": "ifixit_en_all_2025-12.zim"},
        9: {"file": "ifixit_es_all_2026-03.zim"},
        26: {"file": "hesperian"},
    }
    s._mirror = frozenset({11, 12})
    s._mirror_state, s._mirror_detail = "ok", "synthetic"
    s._mirror_lock = threading.Lock()
    s._excl_stats = None

    ok = fail = 0

    def check(name, got, want, _unused="", note=""):
        nonlocal ok, fail
        if got == want:
            ok += 1
            print("  ok    %-8s %-24s %s" % (name, repr(got), note))
        else:
            fail += 1
            print("  FAIL  %-8s got %r, want %r  %s" % (name, got, want, note))

    def ex(src, dnum, path):
        return s.excluded({"src": src, "dnum": dnum, "path": path})

    # --- iFixit -------------------------------------------------------------
    # THE SHAPE THE ONE-LINE RULE IN DECISIONS.md WOULD HAVE MISSED. 297,175 of
    # the 297,242 user pages start with the segment; only 67 carry a full URL.
    check("ifixit", ex(8, 1, "User/1098034/Don Joseph"), "user_profile",
          "", "leading segment, the 297,175 case")
    check("ifixit", ex(9, 1, "ttps://es.ifixit.com/User/1136102/Greg Hamilton"),
          "user_profile", "", "embedded URL, the 67 case")
    # and the content the artifact is here for is untouched
    check("ifixit", ex(8, 2, "Guide/Install+a+battery/12345"), None, "", "a guide is kept")
    check("ifixit", ex(8, 3, "Device/15%s_MacBook_Pro_(Early_2006)" % "″"),
          None, "", "a device is kept")
    check("ifixit", ex(9, 4, "Desmontaje/2016+Moto+Z+Teardown/144150"), None,
          "", "a teardown is kept")
    # A PAGE ABOUT USERS IS NOT A USER PAGE.
    check("ifixit", ex(8, 5, "Guide/How+to+add+a+User+account/99"), None,
          "", "'User' mid-title is not the User/ tree")

    # --- wikem --------------------------------------------------------------
    check("wikem", ex(4, 1, "100kg_(large_Adult)/vi"), "translation")
    check("wikem", ex(4, 2, "Advil/ru"), "translation")
    check("wikem", ex(4, 3, "Advil/zh"), "translation")
    check("wikem", ex(4, 4, "Advil/es"), None, "", "Spanish is kept, Juan 09-11")
    check("wikem", ex(4, 5, "Advil"), None, "", "the English original is kept")
    # THE NAMED-LIST RULE, STATED AS A TEST. A two-letter final segment that is
    # not a language we dropped is SHOWN. Failing toward showing is the safe
    # direction, and this is the assertion that says so out loud.
    check("wikem", ex(4, 6, "Vitamin/b6"), None, "", "unknown 2-char tail is shown")
    check("wikem", ex(4, 7, "Something/is"), None, "", "'is' is not in the list")
    check("wikem", len(s.WIKEM_DROP), 14, "", "fourteen languages dropped")
    check("wikem", "es" in s.WIKEM_DROP, False, "", "es is never in the drop list")
    check("wikem", "en" in s.WIKEM_DROP, False, "", "en carries no suffix at all")

    # --- mdwiki -------------------------------------------------------------
    check("mdwiki", ex(1, 11, "Oral_rehydration_therapy"), "mirror")
    check("mdwiki", ex(1, 99, "Enoxaparin"), None, "", "mdwiki-only article is kept")
    # SHARING A PATH IS NO LONGER ENOUGH, WHICH IS THE 09-12 NARROWING.
    # dnum 77 stands for an article wikipedia_en_medicine also has at the same
    # path, whose mdwiki version carries an infobox the newer one lost -
    # Tafamidis, Fixed_drug_reaction - so it is NOT in the generated set and is
    # shown. Under the one-day-old "same path" rule it would have been dropped.
    check("mdwiki", ex(1, 77, "Tafamidis"), None,
          "", "shared path but not in the set: both copies are shown")
    # AND THE RULE IS ONE-DIRECTIONAL. wikipedia_en_medicine is the artifact
    # being kept; excluding both sides of a mirror would remove the article.
    check("mdwiki", ex(2, 11, "Oral_rehydration_therapy"), None,
          "", "the newer side is never excluded")

    # --- the generated set, when it is not there or not trustworthy ----------
    # EVERY FAILURE PATH MUST SHOW BOTH COPIES, NOT HIDE ONE. A stale set points
    # at documents nobody compared, so the rule is switched off rather than
    # applied - and `mirror_state` says which of the two zeroes this is.
    import tempfile
    _keep = (s._mirror, s._mirror_state)
    try:
        s._mirror = None
        s._mirror_state = s._mirror_detail = None
        globals()["MIRROR_SET"] = os.path.join(
            tempfile.gettempdir(), "ark-mirror-does-not-exist.json")
        check("set", ex(1, 11, "Oral_rehydration_therapy"), None,
              "", "no set file: the mirror rule does not fire")
        check("set", s._mirror_state, "absent", "", "and it says why")

        s._mirror = None
        s._mirror_state = s._mirror_detail = None
        bad = os.path.join(tempfile.gettempdir(), "ark-mirror-bad.json")
        with open(bad, "w", encoding="utf-8") as fh:
            fh.write("{not json")
        globals()["MIRROR_SET"] = bad
        check("set", ex(1, 11, "Oral_rehydration_therapy"), None,
              "", "unreadable set: the rule does not fire")
        check("set", s._mirror_state, "unreadable", "", "and it says why")

        s._mirror = None
        s._mirror_state = s._mirror_detail = None
        stale = os.path.join(tempfile.gettempdir(), "ark-mirror-stale.json")
        with open(stale, "w", encoding="utf-8") as fh:
            json.dump({"dnums": [11, 12], "old": {"jsonl": "nope-old.jsonl"},
                       "new": {"jsonl": "nope-new.jsonl"},
                       "stamp": {"old_jsonl": {"size": 1, "mtime": 1},
                                 "new_jsonl": {"size": 1, "mtime": 1},
                                 "provenance": {"size": 1, "mtime": 1}}}, fh)
        globals()["MIRROR_SET"] = stale
        check("set", ex(1, 11, "Oral_rehydration_therapy"), None,
              "", "stale set: the rule does not fire")
        check("set", s._mirror_state, "stale", "", "and it says why")
    finally:
        globals()["MIRROR_SET"] = _MIRROR_SET_REAL
        s._mirror, s._mirror_state = _keep

    # --- an archive without the pair (the starter kit) ------------------------
    _arts = s.artifacts
    try:
        s.artifacts = {8: {"file": "ifixit_en_all_2025-12.zim"}}
        s._mirror = None
        s._mirror_state = s._mirror_detail = None
        globals()["MIRROR_SET"] = os.path.join(
            tempfile.gettempdir(), "ark-mirror-does-not-exist.json")
        check("set", (s._mirrored_dnums(), s._mirror_state, s._mirror_detail),
              (frozenset(), "not_needed", None), "",
              "no mdwiki in the archive: nothing to compare, not degraded")
    finally:
        globals()["MIRROR_SET"] = _MIRROR_SET_REAL
        s.artifacts = _arts
        s._mirror, s._mirror_state = _keep

    # --- everything else ----------------------------------------------------
    check("other", ex(26, 1, "en_cgeh_2012_full.pdf"), None, "", "PDF shelves untouched")
    check("other", s.excluded({"src": 404, "dnum": 1, "path": "x"}), None,
          "", "an unknown artifact is shown, not hidden")

    # --- the switch ---------------------------------------------------------
    # ARK_NO_FILTERS=1 HAS TO TURN OFF ALL THREE, not two of them. A measurement
    # comparing with and against a partially-disabled filter would be worse than
    # no measurement, because it would look like one.
    try:
        Store.EXCLUDE_OFF = True
        check("switch", ex(8, 1, "User/1/x"), None, "", "iFixit off")
        check("switch", ex(4, 1, "Advil/vi"), None, "", "wikem off")
        check("switch", ex(1, 11, "Oral_rehydration_therapy"), None, "", "mdwiki off")
    finally:
        Store.EXCLUDE_OFF = os.environ.get("ARK_NO_FILTERS") == "1"

    # --- PQ coverage --------------------------------------------------------
    # THE FIXTURE IS THE REAL 2026-09-24 SHAPE: an index built on 09-15 over the
    # 48 artifacts of passes 1 and 2, and a registry that has since grown two
    # Wikipedias worth 32,147,292 chunks. `pq.state` reads `ok` in that
    # situation, `dense_error` is null and nothing else on the health page says
    # a word, which is the window this check exists to close.
    _man = {"stamp": {"artifacts": [["mdwiki_en_all_maxi_2025-11.zim", 300100, 614604928],
                                    ["wikem_en_all_maxi_2026-07.zim", 302855, 620247168]]}}
    _reg = {"artifacts": {
        "1": {"file": "mdwiki_en_all_maxi_2025-11.zim", "chunks": 300100},
        "4": {"file": "wikem_en_all_maxi_2026-07.zim", "chunks": 302855},
        "49": {"file": "wikipedia_es_all_maxi_2026-05.zim", "chunks": 7004952},
        "50": {"file": "wikipedia_en_all_maxi_2026-02.zim", "chunks": 25142340}}}

    check("pqcov", pq_coverage(_man, _reg),
          (602955, 32750247, ["wikipedia_en_all_maxi_2026-02.zim",
                              "wikipedia_es_all_maxi_2026-05.zim"]),
          "", "an index one pass behind is NAMED, not counted")

    # AN EMPTY `missing` IS THE HEALTHY ANSWER AND IT IS NOT THE SAME VALUE AS
    # None. serve.py branches on the list, so a check that returned None for
    # "no gap" and None for "no manifest" would report the same thing twice.
    _full = {"stamp": {"artifacts": [[a["file"], a["chunks"], 0]
                                     for a in _reg["artifacts"].values()]}}
    check("pqcov", pq_coverage(_full, _reg), (32750247, 32750247, []),
          "", "a current index: covered == total, nothing named")

    # DRIFT IS THE OTHER DIRECTION AND IS NOT THIS CHECK'S JOB. _pq_plan()
    # already catches a vector file that moved, by size, and refuses to load.
    # Counting it here too would put one fault in two voices.
    _extra = {"stamp": {"artifacts": [["gone_from_the_registry.zim", 5, 0],
                                      ["mdwiki_en_all_maxi_2025-11.zim", 300100, 0]]}}
    check("pqcov", pq_coverage(_extra, _reg)[0], 300100,
          "", "an artifact only the MANIFEST has is ignored")

    # A REGISTRY ROW WITH NO COUNT MUST NOT SILENTLY BECOME A COVERED ONE.
    check("pqcov", pq_coverage(_man, {"artifacts": {
              "9": {"file": "half_written.zim"}}}),
          (0, 0, ["half_written.zim"]), "", "no `chunks` key counts as zero, still named")

    check("pqcov", pq_coverage({}, _reg)[2] == sorted(
              a["file"] for a in _reg["artifacts"].values()), True,
          "", "no stamp at all: every artifact is missing, and none is dropped")

    print("\n%d/%d" % (ok, ok + fail))
    return fail == 0


if __name__ == "__main__":
    import sys
    if "--selftest" in sys.argv:
        sys.exit(0 if selftest() else 1)
    print(__doc__.strip().splitlines()[0])
    print("usage: python store.py --selftest")
